'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property studentID As Integer
    Public Property studentName As String
    Public Property age As Integer
    Public Property standardID As Nullable(Of Integer)

    Public Overridable Property Standard As Standard

End Class
